services:
  acme-widget-php:
    build:
      context: .
    container_name: acme-widget-php
    command: bash -c "composer install && vendor/bin/phpunit && vendor/bin/phpstan analyse"
    volumes:
      - .:/app
    ports:
      - "8088:80"
